In [1]:
import pandas as pd
import joblib
from preprocessing_utils import preprocess_churn_data

In [2]:
xgb_model, scaler, encoders = joblib.load("xgb_churn_model.pkl")

new_data = pd.read_csv("customer_churn_dataset-testing-master.csv")

In [3]:
new_data.shape

(64374, 12)

In [4]:
new_data.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,1,22,Female,25,14,4,27,Basic,Monthly,598,9,1
1,2,41,Female,28,28,7,13,Standard,Monthly,584,20,0
2,3,47,Male,27,10,2,29,Premium,Annual,757,21,0
3,4,35,Male,9,12,5,17,Premium,Quarterly,232,18,0
4,5,53,Female,58,24,9,2,Standard,Annual,533,18,0

In [5]:
X_new, _, _, _, customer_ids = preprocess_churn_data(
    new_data,
    is_train=False,
    scaler=scaler,
    encoders=encoders
)

In [6]:
churn_pred = xgb_model.predict(X_new)

churn_prob = xgb_model.predict_proba(X_new)[:, 1]

results = pd.DataFrame({
    'CustomerID': customer_ids,
    'Predicted_Churn': churn_pred,
    'Churn_Probability': churn_prob
})

results.head()

   CustomerID  Predicted_Churn  Churn_Probability
0           1                1           1.000000
1           2                1           1.000000
2           3                1           0.999837
3           4                1           1.000000
4           5                1           1.000000

In [7]:
results.to_csv("cust1_churn_predictions.csv", index=False)
print("Predictions saved to churn_predictions.csv")

Predictions saved to churn_predictions.csv